leagues:
  baseball-kbo:
    teams:
      - 'Doosan Bears'
      - 'Hanwha Eagles'
      - 'KT Wiz'
      - 'LG Twins'
      - 'Lotte Giants'
      - 'NC Dinos'
      - 'Samsung Lions'
      - 'SK Wyverns'
      - 'Kiwoom Heroes'
      - 'Kia Tigers'
  
  baseball-npb:
    teams:
      - 'Hokkaido Nippon-Ham Fighters'
      - 'Chiba Lotte Marines'
      - 'Fukuoka SoftBank Hawks'
      - 'Hiroshima Toyo Carp'
      - 'Orix Buffaloes'
      - 'Yokohama DeNA BayStars'
      - 'Tokyo Yakult Swallows'
      - 'Yomiuri Giants'
      - 'Seibu Lions'
      - 'Tohoku Rakuten Golden Eagles'
  
  baseball-mlb:
    teams:
      - 'Arizona Diamondbacks'
      - 'Atlanta Braves'
      - 'Baltimore Orioles'
      - 'Boston Red Sox'
      - 'Chicago White Sox'
      - 'Chicago Cubs'
      - 'Cincinnati Reds'
      - 'Cleveland Guardians'
      - 'Colorado Rockies'
      - 'Detroit Tigers'
      - 'Houston Astros'
      - 'Kansas City Royals'
      - 'Los Angeles Angels'
      - 'Los Angeles Dodgers'
      - 'Miami Marlins'
      - 'Milwaukee Brewers'
      - 'Minnesota Twins'
      - 'New York Mets'
      - 'New York Yankees'
      - 'Oakland Athletics'
      - 'Philadelphia Phillies'
      - 'Pittsburgh Pirates'
      - 'San Diego Padres'
      - 'San Francisco Giants'
      - 'Seattle Mariners'
      - 'St. Louis Cardinals'
      - 'Tampa Bay Rays'
      - 'Texas Rangers'
      - 'Toronto Blue Jays'
      - 'Washington Nationals'
  
  basektball-nba:
    teams:
      - 'Atlanta Hawks'
      - 'Boston Celtics'
      - 'Brooklyn Nets'
      - 'Charlotte Hornets'
      - 'Chicago Bulls'
      - 'Cleveland Cavaliers'
      - 'Dallas Mavericks'
      - 'Denver Nuggets'
      - 'Detroit Pistons'
      - 'Golden State Warriors'
      - 'Houston Rockets'
      - 'Indiana Pacers'
      - 'Los Angeles Clippers'
      - 'Los Angeles Lakers'
      - 'Memphis Grizzlies'
      - 'Miami Heat'
      - 'Milwaukee Bucks'
      - 'Minnesota Timberwolves'
      - 'New Orleans Pelicans'
      - 'New York Knicks'
      - 'Oklahoma City Thunder'
      - 'Orlando Magic'
      - 'Philadelphia 76ers'
      - 'Portland Trail Blazers'
      - 'Sacramento Kings'
      - 'San Antonio Spurs'
      - 'Toronto Raptors'
      - 'Utah Jazz'
      - 'Washington Wizards'
  
  football-nfl:
    teams:
      - 'Arizona Cardinals'
      - 'Atlanta Falcons'
      - 'Baltimore Ravens'
      - 'Buffalo Bills'
      - 'Carolina Panthers'
      - 'Chicago Bears'
      - 'Cincinnati Bengals'
      - 'Cleveland Browns'
      - 'Dallas Cowboys'
      - 'Denver Broncos'
      - 'Detroit Lions'
      - 'Green Bay Packers'
      - 'Houston Texans'
      - 'Indianapolis Colts'
      - 'Jacksonville Jaguars'
      - 'Kansas City Chiefs'
      - 'Las Vegas Raiders'
      - 'Los Angeles Chargers'
      - 'Los Angeles Rams'
      - 'Miami Dolphins'
      - 'Minnesota Vikings'
      - 'New England Patriots'
      - 'New Orleans Saints'
      - 'New York Giants'
      - 'New York Jets'
      - 'Philadelphia Eagles'
      - 'Pittsburgh Steelers'
      - 'San Francisco 49ers'
      - 'Seattle Seahawks'
      - 'Tampa Bay Buccaneers'
      - 'Tennessee Titans'
      - 'Washington Commanders'
  
  soccer-efl:
    teams:
      - 'Blackburn Rovers'
      - 'Bristol City'
      - 'Burnley'
      - 'Cardiff City'
      - 'Coventry City'
      - 'Derby County'
      - 'Hull City'
      - 'Leeds United'
      - 'Luton Town'
      - 'Middlesbrough'
      - 'Millwall'
      - 'Norwich City'
      - 'Oxford United'
      - 'Plymouth Argyle'
      - 'Portsmouth'
      - 'Preston North End'
      - 'Queens Park Rangers'
      - 'Sheffield Wednesday'
      - 'Stoke City'
      - 'Sunderland'
      - 'Swansea City'
      - 'Watford'
      - 'West Bromwich Albion'
      - 'Sheffield United'
  
  soccer-epl:
    teams:
    - 'Arsenal'
    - 'Aston Villa'
    - 'Bournemouth'
    - 'Brentford'
    - 'Brighton and Hove Albion'
    - 'Chelsea'
    - 'Crystal Palace'
    - 'Everton'
    - 'Fulham'
    - 'Ipswich Town'
    - 'Leicester City'
    - 'Liverpool'
    - 'Manchester City'
    - 'Manchester United'
    - 'Newcastle United'
    - 'Nottingham Forest'
    - 'Southampton'
    - 'Tottenham Hotspur'
    - 'West Ham United'
    - 'Wolverhampton Wanderers'
  
  soccer-ucl:
    teams:
    - 'Arsenal FC'
    - 'Aston Villa FC'
    - 'Atalanta BC'
    - 'Club Atlético de Madrid'
    - 'FC Barcelona'
    - 'FC Bayern München'
    - 'SL Benfica'
    - 'Bologna FC'
    - 'Stade Brestois 29'
    - 'Celtic FC'
    - 'Club Brugge'
    - 'Borussia Dortmund'
    - 'Feyenoord'
    - 'Girona FC'
    - 'FC Internazionale Milano'
    - 'Juventus'
    - 'RB Leipzig'
    - 'Bayer 04 Leverkusen'
    - 'Liverpool FC'
    - 'Manchester City'
    - 'AC Milan'
    - 'AS Monaco FC'
    - 'Paris Saint-Germain'
    - 'PSV Eindhoven'
    - 'Real Madrid CF'
    - 'FC Shakhtar Donetsk'
    - 'Sporting Clube de Portugal'
    - 'SK Sturm Graz'
    - 'VfB Stuttgart'
    - 'FK Crvena zvezda'
    - 'GNK Dinamo'
    - 'Galatasaray A.Ş.'
    - 'BSC Young Boys'
    - 'APOEL FC'
    - 'FK Bodø/Glimt'
    - 'FC Dynamo Kyiv'
    - 'FCSB'
    - 'Fenerbahçe SK'
    - 'Ferencvárosi TC'
    - 'Jagiellonia Białystok'
    - 'LOSC Lille'
    - 'PFC Ludogorets 1945'
    - 'Malmö FF'
    - 'FC Midtjylland'
    - 'PAOK FC'
    - 'Qarabağ FK'
    - 'Rangers FC'
    - 'FC Salzburg'
    - 'SK Slavia Praha'
    - 'ŠK Slovan Bratislava'
    - 'AC Sparta Praha'
    - 'FC Twente'
    - 'R. Union Saint-Gilloise'
    - 'FK Borac Banja Luka'
    - 'NK Celje'
    - 'FC Dinamo Minsk'
    - 'KÍ Klaksvík'
    - 'Lincoln Red Imps FC'
    - 'FC Lugano'
    - 'Maccabi Tel Aviv FC'
    - 'FK Panevėžys'
    - 'FK Partizan'
    - 'FC Petrocub-Hincesti'
    - 'FC RFS'
    - 'Shamrock Rovers FC'
    - 'The New Saints FC'
    - 'UE Santa Coloma'
    - 'FC Ballkani'
    - 'FK Dečić'
    - 'FC Differdange 03'
    - 'FC Dinamo Batumi'
    - 'KF Egnatia'
    - 'FC Flora Tallinn'
    - 'Hamrun Spartans FC'
    - 'HJK Helsinki'
    - 'Larne FC'
    - 'FC Ordabasy Shymkent'
    - 'FC Pyunik'
    - 'FC Struga'
    - 'Víkingur Reykjavík'
    - 'Virtus AC'
  
  hockey-nhl:
    teams:
      - 'Anaheim Ducks'
      - 'Arizona Coyotes'
      - 'Boston Bruins'
      - 'Buffalo Sabres'
      - 'Calgary Flames'
      - 'Carolina Hurricanes'
      - 'Chicago Blackhawks'
      - 'Colorado Avalanche'
      - 'Columbus Blue Jackets'
      - 'Dallas Stars'
      - 'Detroit Red Wings'
      - 'Edmonton Oilers'
      - 'Florida Panthers'
      - 'Los Angeles Kings'
      - 'Minnesota Wild'
      - 'Montreal Canadiens'
      - 'Nashville Predators'
      - 'New Jersey Devils'
      - 'New York Islanders'
      - 'New York Rangers'
      - 'Ottawa Senators'
      - 'Philadelphia Flyers'
      - 'Pittsburgh Penguins'
      - 'San Jose Sharks'
      - 'Seattle Kraken'
      - 'St. Louis Blues'
      - 'Tampa Bay Lightning'
      - 'Toronto Maple Leafs'
      - 'Vancouver Canucks'
      - 'Vegas Golden Knights'
      - 'Washington Capitals'
      - 'Winnipeg Jets'
  
  soccer-mls:
    teams:
      - 'Atlanta United FC'
      - 'Austin FC'
      - 'CF Montréal'
      - 'Charlotte FC'
      - 'Chicago Fire FC'
      - 'Colorado Rapids'
      - 'Columbus Crew'
      - 'D.C. United'
      - 'FC Cincinnati'
      - 'FC Dallas'
      - 'Houston Dynamo FC'
      - 'Inter Miami CF'
      - 'LA Galaxy'
      - 'LAFC'
      - 'Minnesota United FC'
      - 'Nashville SC'
      - 'New England Revolution'
      - 'New York City FC'
      - 'New York Red Bulls'
      - 'Orlando City SC'
      - 'Philadelphia Union'
      - 'Portland Timbers'
      - 'Real Salt Lake'
      - 'San Jose Earthquakes'
      - 'Seattle Sounders FC'
      - 'Toronto FC'
      - 'Vancouver Whitecaps FC'
